---
name: Main Build Pipeline

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  markdown:
    name: Markdown Lint
    uses: ikostan/2d_platformer_tutorial/.github/workflows/markdown_lint.yml@main
  yamllint:
    name: YAML Lint
    uses: ikostan/2d_platformer_tutorial/.github/workflows/yamllint.yml@main
